### ISSUE TITLE
Hide your api key

### ISSUE THREAD

**Issue by Touseef-ahmad-arbisoft** [shemmee/React-Weather-App#5]
your api key is exposed in the codebase, please remove it and close the api key!

**Comment by s-shemmee** [comment]
Hey @Touseef-ahmad-arbisoft, you're absolutely right. thanks for pointing this out! The API key was intentionally exposed during a coding bootcamp to allow for evaluation of my implementation. Since the bootcamp ended over a year ago, I forgot to secure it afterward. I've now removed the exposed key from the repo’s history. I really appreciate your attention to detail!
